### ISSUE TITLE
機能的要望

### ISSUE THREAD

**Issue by InabaShota** [tonamichan/kappature#1]
1:タスクの検索を可能にしてほしい.
2:gunsmithなどのpartがあるものなどを一括または自動で（現在出ているpart-1を押すと1~part-1まで）クリアできるまたは終わってる可能性のあるものとしてハイライトなどしてほしい.

memo:
書き方がようわからん

**Comment by tonamichan** [comment]
Issue起票助かります！

サンプルを兼ねて、私の方で頂いた要望ごとにIssueを立て直しますね👌

**Comment by tonamichan** [comment]
https://github.com/tonamichan/kappa_chan/issues/2
https://github.com/tonamichan/kappa_chan/issues/3
に分割したのでこちらはCloseにします 👍
